### ISSUE TITLE
커뮤니티 섹션 리팩토링 및 반응형 구현

### ISSUE THREAD

**Issue by chigomuh** [FILMDOM-s/film-doms#15]
<작업 내용>
- 커뮤니티 섹션을 리팩토링합니다.
- 커뮤니티 섹션을 추가된 디자인 시안과 같이 반응형으로 구현합니다.

**Comment by thewoowon** [comment]
해당 이슈 리뷰 후 develop에 안전하게 머지 되었으므로 닫도록 하겠습니다.
