### ISSUE TITLE
메인 페이지 community 섹션과 다른 섹션의 너비가 다른 이슈 및 섹션간의 간격 조정

### ISSUE THREAD

**Issue by chigomuh** [FILMDOM-s/film-doms#24]
<이슈 내용>
- 디자인 시안과 달리 다른 섹션에 비해 커뮤니티 섹션의 너비가 작습니다.
- 디자인 시안과 달리 섹션간의 간격이 좁습니다.

<첨부>
- 메인 페이지 커뮤니티 섹션 너비 및 섹션 간격
![before-fix](https://user-images.githubusercontent.com/84620459/221415830-3ae647f0-5939-4a95-a5c8-2bd074b5d60a.PNG)

**Comment by thewoowon** [comment]
코드 리뷰 후에 머지 완료한 내용으로 이슈 닫도록 하겠습니다.
