### ISSUE TITLE
og tag 컴포넌트로 만들어 재사용 가능하게 합니다

### ISSUE THREAD

**Issue by chigomuh** [FILMDOM-s/film-doms#26]
<작업 내용>
- 페이지별로 OG 태그를 매번 작성해야하는 불편함을 덜기위해 컴포넌트를 구현합니다.

**Comment by thewoowon** [comment]
og 이미 구현하셨나요? 도움 필요하시면 말해주세요~
pages/temp에 og에 필요한 5가지 정도는 이미 정의했기 때문에 분리 작업과 props화 하는 작업만 하면 될 것 같습니다.

url, type, title, description,image 다섯가지 나오네요.
