### ISSUE TITLE
_app 파일을 리팩토링 하려고 합니다.

### ISSUE THREAD

**Issue by chigomuh** [FILMDOM-s/film-doms#27]
<제안 내용>
- 현재, _app.tsx 파일에는 route의 변경, serviceworker 상태 등 분리하여 관리하면 가독성이 좋을 것 같습니다.
- Script 컴포넌트도 하나의 커스텀 Script로 분리하여 관리하면 좋을 것 같습니다

의견 남겨주시거나 승인하시면 바로 작업하겠습니다.

**Comment by thewoowon** [comment]
동의합니다. gtag 관련한 코드 좀 신경쓰였는데.. 매의눈이네요

**Comment by chigomuh** [comment]
> 동의합니다. gtag 관련한 코드 좀 신경쓰였는데.. 매의눈이네요

한번 작업해보고 어려움이 있다면 도움 청하겠습니다!

**Comment by SH-Lee2** [comment]
좋습니다~!!

**Comment by thewoowon** [comment]
머지된 제안으로 배포 후 테스트를 통해 검증하도록 하겠습니다.
