### ISSUE TITLE
영화 전체 게시판 구현

### ISSUE THREAD

**Issue by chigomuh** [FILMDOM-s/film-doms#57]
영화 전체 게시판의 디자인과 기능을 구현합니다.
- [x] 페이지네이션
- [x] 태그별 필터링
- [x] 검색
- [x] 데이터 렌더링(table), 스타일링
- [x] mock data 생성
- [x] 레이아웃 잡기
- [x] 구조 잡기

<참고>
- 필름 유니버스 게시판과 동일한 디자인을 가집니다. -> 추후 추가될 게시판도 동일한 디자인을 가질 가능성이 존재
![image](https://user-images.githubusercontent.com/84620459/228163714-22d5faf6-a921-4932-834a-ea81b16b0c9c.png)

- [피그마](https://www.figma.com/file/Xip10NzGFcSPqZb7QyjN6v/%ED%95%84%EB%A6%84%EB%8D%A4%EC%A6%88_Home?node-id=0-1&t=41GEfstBhpaWlpEM-0)

- 기획서(영화전체게시판)
![image](https://user-images.githubusercontent.com/84620459/227989579-654cf07c-8d44-4276-be87-7b338a19d8f5.png)

**Comment by thewoowon** [comment]
기능 단위로 개발 진행해야겠죠?
템플릿 구성(그리드 작업)이 먼저 선행되어야 할 것 같아요.
업무 분담에 대해 서로 상의 진행하면 될 것 같습니다.
스토리북 작업은 오늘 내로 마친 후 수정 커밋 추가로 덧붙이겠습니다.
감사합니다.
