### ISSUE TITLE
Largest Contentful Paint element 대응

### ISSUE THREAD

**Issue by thewoowon** [FILMDOM-s/film-doms#59]
Largest Contentful Paint element warining 발생으로
remote image를 활용할 경우 width와 height를 선행 입력 후
priority를 설정하면 로딩을 우선하고 성능 향상으로 이어진다고 하네요.

배너 이미지와 푸터 이미지에 priority 속성 적용

- #53

**Comment by chigomuh** [comment]
footer 이미지는 하단에 보여져서 priority 속성이 없어도 될 것 같은데 어떻게 생각하시나요?
[kakao-fe/lazy-loading](https://fe-developers.kakaoent.com/2022/220714-next-image/#lazy-loading)

**Comment by thewoowon** [comment]
푸터는 생략하고 배너 쪽만 진행하겠습니다.
감사합니다.
